{{- if .Values.app.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-data
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "agro-shop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.app.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.size }}
  {{- if .Values.app.persistence.storageClass }}
  storageClassName: {{ .Values.app.persistence.storageClass }}
  {{- end }}
{{- end }}